name: twillio_dart
version: 0.0.3
author: Marcos Placona <hi@placona.co.uk>
description: An implementation of the Twillio API for Dart
homepage: http://mplacona.github.io/twillio
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  http: '>=0.10.0 <=0.11.0+1'
  mock: any
dev_dependencies:
  unittest: any
